name: Deploy to Synapse on Development Merge

on:
  push:
    branches:
      - development

jobs:
  merge-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the development branch and fetch all branches
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch all branches

      - name: Fetch all branches
        run: git fetch --all

      # Step 2: Merge development into workspace_publish, allowing unrelated histories
      - name: Merge development to workspace_publish
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout workspace_publish
          git merge development --no-ff --allow-unrelated-histories
          git push origin workspace_publish
